### ISSUE TITLE
splitting up paired directional rna-seq files

### ISSUE THREAD

**Issue by colindaven** [compgen-io/ngsutilsj#10]
Hi,

I used the first python version to split up paired directionally sequenced rna-seq files into two files (forward paired reads only, reverse paired reads only).

Does this functionality still exist (to use a filter file), or do you have to specify flags similar to samtools in the modern ngsutilsj version ? 

Thanks.

This was a json file used back in 2015:

```
{
"filters" : [    
  {"id" : "FirstinPair",
   "isFirstMate" : "true"
  },     
  {"id" : "R",
   "isReverseStrand" : "false"
  },
  {"id" : "S",
   "isReverseStrand" : "true"
  },
  {"id" : "SecondinPair",
   "isFirstMate" : "false"
  },
  {"id" : "P",
   "isPaired" : "true"
  }
],
"rule": "( P & FirstinPair & R) | ( P & SecondinPair & S)"
}

```

**Comment by mbreese** [comment]
The current Java version requires command line arguments (similar to samtools). I’m pretty sure that there wasn’t a JSON definition of filters in the Python version, but maybe I’m misremembering. ngsutils/ngsutils/bam/filter.py at master · ngsutils/ngsutilsgithub.comOn Jul 26, 2023, at 4:23 AM, Colin Davenport ***@***.***> wrote:﻿
Hi,
I used the first python version to split up paired directionally sequenced rna-seq files into two files.
Does this functionality still exist (to use a filter file), or do you have to specify flags similar to samtools in the modern ngsutilsj version ?
Thanks.
This was a json file used back in 2015:
{
"filters" : [    
  {"id" : "FirstinPair",
   "isFirstMate" : "true"
  },     
  {"id" : "R",
   "isReverseStrand" : "false"
  },
  {"id" : "S",
   "isReverseStrand" : "true"
  },
  {"id" : "SecondinPair",
   "isFirstMate" : "false"
  },
  {"id" : "P",
   "isPaired" : "true"
  }
],
"rule": "( P & FirstinPair & R) | ( P & SecondinPair & S)"
}

**Comment by colindaven** [comment]
Ok, thanks (maybe I was mistaken and it was bamtools or similar ??). I found a documented way to do it in samtools now as well on biostars, so no worries. 

https://www.biostars.org/p/92935/
