### ISSUE TITLE
Weird for loop

### ISSUE THREAD

**Issue by hsiaoyi0504** [compgen-io/ngsutilsj#3]
It seems to me that the for loop is redundant.

https://github.com/compgen-io/ngsutilsj/blob/204ba26528cd9a1a245a700e91673646b0108cf1/src/java/io/compgen/ngsutils/bam/filter/UniqueStart.java#L26-L32

**minusPos** which was declared in 
https://github.com/compgen-io/ngsutilsj/blob/204ba26528cd9a1a245a700e91673646b0108cf1/src/java/io/compgen/ngsutils/bam/filter/UniqueStart.java#L11

wasn't change before that, that is `minusPos.size()` is 0 and the for loop will not actually start running.

**Comment by mbreese** [comment]
The minus positions are tracked as reads are processed. So, you're right that for the first read, this loop won't run. However, for the second minus strand read, it will run.

```
41        if (read.getReadNegativeStrandFlag()) {
42            minusPos.add(read.getAlignmentEnd());
43            Collections.sort(minusPos);
44        } else {

```

So, this class maintains state between reads... or another way to stay this, is that it keeps track of what minus strand reads have been outputted for a given window. If the current read is beyond that window *or* doesn't match any other positions in that window, it is outputted and added to the list.

Does that help?

**Comment by hsiaoyi0504** [comment]
I got it ! Thanks !
