### ISSUE TITLE
Where is the removeclipping tool?

### ISSUE THREAD

**Issue by wynstep** [compgen-io/ngsutilsj#4]
Hello,
did you add also the possibility to remove the clipped reads from the BAM file?

Thanks

**Comment by mbreese** [comment]
Not all of the functions in the original python ngsutils was ported over to
the Java version. Is this a feature that you're missing?
--
Marcus Breese

**Comment by wynstep** [comment]
For the purpose of my research project I would say "yes", this is a feature I am missing. 
Could it be possible to perform the porting of this feature, please?

**Comment by mbreese** [comment]
This feature has been ported over.  See the new release for a downloadable version!
