### ISSUE TITLE
New version of ngsutilsj doesn't have --whitelist option? 

### ISSUE THREAD

**Issue by akimmitt** [compgen-io/ngsutilsj#5]
Hello, 

I am using ngutils to filter bam files using an intersection file. My original script included the option --whitelist to include this intersection file; however it does not appear that --whitelist is an option any longer. Is there an alternative? 
Here is my script: 

\$path/ngsutilsj bam-filter --whitelist \$realign_bam_final_par1/"$prefix"_intersection.txt \$realign_bam_final_par2/"$prefix".realigned.q30.bam \$realign_bam_final_par2/"$prefix".realigned.q30.unbiased.bam

I also tried to download an older version but then my build (using ant jar) kept failing. 

Thanks!

**Comment by mbreese** [comment]
Late comment, but to leave it for the future: there is an `--include` argument for bam-filter which has the same functionality.
